### ISSUE TITLE
ideas for block contents: industrial, shops

### ISSUE THREAD

**Issue by sofar** [echurchill/WorldEdit_City#2]
See topic. Especially some industrial blocks like factories may be cool and easy to generate.

**Comment by echurchill** [comment]
I am sorry I missed you comments/topic until just now. I started on some procedural industrial and retail lots but stopped when the template pasting got incorporated... everybody had specific needs and wants and I figured it would be best to let them create their dreams themselves. In hindsight I think it would have been nice if I had continued on both fronts... maybe I will pick the effort again.

**Comment by sofar** [comment]
No worries. I have moved on to Minetest development a while back, and closed out some old issues. All the best.
